[package]
name = "yitizi"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.117"

[build-dependencies]
build_lib = { path = "build_lib" }
serde_json = "1.0.117"

[profile.release.build-override]
opt-level = 3

[profile.dev.build-override]
opt-level = 3
